# config MongoDB

spring.data.mongodb.uri=mongodb://root:mongo123@localhost:27017/productdb?authSource=admin
spring.data.mongodb.database=productdb
spring.data.mongodb.auto-index-creation=true

# Disable JPA when Mongo is active
spring.autoconfigure.exclude=\
  org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,\
  org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration,\
  org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration
